spring:
  profiles:
    active: mysql

spring.batch.job.names: ${job.name:NONE}

logging:
  level:
    root: info
#    org:
#      springframework:
#        batch:
#          item:
#            database: debug

    org:
      springframework:
        jdbc:
          core:
            JdbcTemplate: debug

---
spring:
  profiles: local
  datasource:
    hikari:
      jdbc-url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
      username: sa
      password:
      driver-class-name: org.h2.Driver
---
spring:
  profiles: mysql
  datasource:
    hikari:
      jdbc-url: jdbc:mysql://localhost:3306/ddori_db?useSSL=false&serverTimezone=UTC&autoReconnect=true&allowPublicKeyRetrieval=true&useSSL=false
      username: root
      password: ddoriek7818
      driver-class-name: com.mysql.cj.jdbc.Driver